version: '3.7'
services:
  postgres:
    image: "postgres:13"
    ports:
      - '127.0.0.1:5432:5432'
    container_name: customer_find_provider_postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - customer_find_provider_data:/var/lib/postgresql/data
volumes:
  customer_find_provider_data: